name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "warning"
env:
  DOCU_NOTION_INTEGRATION_TOKEN: "${{ secrets.DOCU_NOTION_INTEGRATION_TOKEN }}"
  DOCU_NOTION_SAMPLE_ROOT_PAGE: "${{ secrets.DOCU_NOTION_SAMPLE_ROOT_PAGE }}"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm i --legacy-peer-deps
      - name: Install dependencies
        run: echo DOCU_NOTION_INTEGRATION_TOKEN : $DOCU_NOTION_INTEGRATION_TOKEN
        run: echo DOCU_NOTION_SAMPLE_ROOT_PAGE : $DOCU_NOTION_SAMPLE_ROOT_PAGE
      - name: Pull latest from Notion
        run: npm run pull:latest
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply changes from blog-notion
      - name: Build github pages branch
        run: npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
